services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3100:3100'
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app-network
    # Add healthcheck
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3100',
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
